version: "3.9"

services:
  translator:
    image: huggingface/transformers-pytorch-gpu
    volumes:
      - .:/workspace
      - huggingface:/root/.cache/huggingface
    working_dir: /workspace
    expose:
      - 8000
    command: make install run
    networks:
      - translation
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  discord:
    build: .
    user: node
    restart: always
    env_file:
      - ./.env
    volumes:
      - .:/home/node
      - ./node_modules:/home/node/node_modules
    networks:
      - translation
    depends_on:
      - translator

networks:
  translation:

volumes:
  huggingface: